# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-05 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.TextField()),
                ('date', models.TextField()),
                ('symptoms', models.TextField()),
                ('diagnosis', models.TextField()),
                ('medicine', models.TextField()),
                ('procedure', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_id', models.TextField()),
                ('is_valid', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='patient_data',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Patient_Id'),
        ),
    ]
