# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-05 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180505_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_id',
            name='random_id',
        ),
    ]
