# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-27 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummymodel',
            name='random_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
