# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-29 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.TextField(),
        ),
    ]
